### ISSUE TITLE
Automatically re-tag ID3 2.2 to 2.3

### ISSUE THREAD

**Issue by kirbyfan64** [vanilla-music/vanilla-music-tag-editor#13]
Related discussion here:

https://github.com/vanilla-music/vanilla/issues/609#issuecomment-307056273

**Comment by Adonai** [comment]
okay, time to dig it

**Comment by Adonai** [comment]
Sorry, @kirbyfan64 , do you, eh, happen to have sample file for that? Because apparently I don't X_X:

```
Music $ grep -UP "\x49\x44\x33\x02" **/*.mp3
Music $
```

**Comment by Adonai** [comment]
This should be working by now because I'm so good at writing bug-free code (even without any sample files or tests!) that you'll certainly won't encounter any bugs. If you see them nevertheless then universe has altered the way it does things and this feature broke. Anyway, feel free to re-open it in case of any issues.

**Comment by Adonai** [comment]
You can grab it from [latest release](https://github.com/vanilla-music/vanilla-music-tag-editor/releases) or wait for F-Droid to build it if you don't want to mess with signatures and reinstalls.
